#!/usr/bin/env node
/*
  build.js — bundles particle-zoo into a single self-contained HTML file
  at mobile/index.html. Run with: node build.js  (from particle-zoo/)

  Also generates mobile/particle-zoo.html as a redundant name so you
  can copy the file anywhere and open it directly on a phone.
*/
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT_DIR = path.join(ROOT, 'mobile');
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

const html   = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const css    = fs.readFileSync(path.join(ROOT, 'styles.css'), 'utf8');
const i18nJs = fs.readFileSync(path.join(ROOT, 'i18n.js'), 'utf8');
const appJs  = fs.readFileSync(path.join(ROOT, 'app.js'), 'utf8');

// 1) replace <link rel="stylesheet" href="styles.css" /> with inline <style>
let out = html.replace(
  /<link\s+rel="stylesheet"\s+href="styles\.css"\s*\/?>/,
  `<style>\n${css}\n</style>`
);

// 2) replace <script src="i18n.js"></script> and <script src="app.js"></script>
out = out.replace(
  /<script\s+src="i18n\.js"><\/script>/,
  `<script>\n${i18nJs}\n</script>`
);
out = out.replace(
  /<script\s+src="app\.js"><\/script>/,
  `<script>\n${appJs}\n</script>`
);

// 3) Inject a small banner comment at the top
const banner =
`<!--
  Particle Zoo — SINGLE-FILE BUILD
  Generated by build.js from index.html + styles.css + i18n.js + app.js
  Do NOT edit this file directly; edit the source files and re-run:
      node build.js
  Source: https://github.com/micwu-personal/Physics
-->
`;
out = out.replace(/^<!DOCTYPE html>/i, `<!DOCTYPE html>\n${banner}`);

const outPath1 = path.join(OUT_DIR, 'index.html');
const outPath2 = path.join(OUT_DIR, 'particle-zoo.html');
fs.writeFileSync(outPath1, out);
fs.writeFileSync(outPath2, out);

const sizeKB = (Buffer.byteLength(out, 'utf8') / 1024).toFixed(1);
console.log(`✓ Wrote ${outPath1} (${sizeKB} KB)`);
console.log(`✓ Wrote ${outPath2} (${sizeKB} KB)`);
console.log(`\nOpen either file directly in a browser or transfer to a phone.`);
