#!/usr/bin/env node
/*
  build.js — bundles particle-zoo into a single self-contained HTML file
  at mobile/index.html. Run with: node build.js  (from particle-zoo/)

  Also generates mobile/particle-zoo.html as a redundant name so you
  can copy the file anywhere and open it directly on a phone.
*/
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT_DIR = path.join(ROOT, 'mobile');
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

const html   = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const css    = fs.readFileSync(path.join(ROOT, 'styles.css'), 'utf8');
const coreJs = fs.readFileSync(path.join(ROOT, 'physics-core.js'), 'utf8');
const refsJs = fs.readFileSync(path.join(ROOT, 'references.js'), 'utf8');
const i18nJs = fs.readFileSync(path.join(ROOT, 'i18n.js'), 'utf8');
const appJs  = fs.readFileSync(path.join(ROOT, 'app.js'), 'utf8');
const brandCss = fs.readFileSync(path.join(ROOT, '..', 'assets', 'brand', 'brand.css'), 'utf8');
const brandSvg = fs.readFileSync(path.join(ROOT, '..', 'assets', 'brand', 'favicon.svg')).toString('base64');

function inlineMedia(source) {
  return source.replace(/\.\.\/assets\/media\/([A-Za-z0-9_.-]+)/g, (match, filename) => {
    const filePath = path.join(ROOT, '..', 'assets', 'media', filename);
    if (!fs.existsSync(filePath)) throw new Error(`Missing media asset: ${filename}`);
    const mime = path.extname(filename).toLowerCase() === '.jpg' ? 'image/jpeg' : 'image/png';
    return `data:${mime};base64,${fs.readFileSync(filePath).toString('base64')}`;
  });
}

function inlineFonts(source) {
  const fontDir = path.join(ROOT, '..', 'assets', 'fonts');
  const fontCss = fs.readFileSync(path.join(fontDir, 'fonts.css'), 'utf8')
    .replace(/url\("\.\/([^"]+)"\)/g, (match, file) => {
      const data = fs.readFileSync(path.join(fontDir, file)).toString('base64');
      return `url("data:font/woff2;base64,${data}")`;
    });
  return source.replace(
    /<link\s+rel="stylesheet"\s+href="\.\.\/assets\/fonts\/fonts\.css"\s*\/?>/,
    `<style>\n${fontCss}\n</style>`
  );
}

// 1) replace <link rel="stylesheet" href="styles.css" /> with inline <style>
let out = html.replace(
  /<link\s+rel="stylesheet"\s+href="styles\.css"\s*\/?>/,
  `<style>\n${css}\n</style>`
);
out = out.replace(
  /<link\s+rel="stylesheet"\s+href="\.\.\/assets\/brand\/brand\.css"\s*\/?>/,
  `<style>\n${brandCss}\n</style>`
);
out = out.replace(
  /<link\s+rel="icon"\s+href="\.\.\/assets\/brand\/favicon\.svg"\s+type="image\/svg\+xml"\s*\/?>/,
  `<link rel="icon" href="data:image/svg+xml;base64,${brandSvg}" type="image/svg+xml">`
);

// 1b) strip all external CDN links (Google Fonts) so the mobile build is
//     fully offline / self-contained. CSS already falls back to system fonts.
out = out.replace(/<link\s+rel="preconnect"[^>]*>\s*/g, '');
out = out.replace(/<link\s+href="https:\/\/fonts\.googleapis\.com[^"]*"\s+rel="stylesheet"[^>]*>\s*/g, '');
out = out.replace(/<link\s+rel="stylesheet"\s+href="https:\/\/fonts\.googleapis\.com[^"]*"[^>]*>\s*/g, '');

// 2) inline source modules in browser execution order.
out = out.replace(
  /<script\s+src="physics-core\.js"><\/script>/,
  `<script>\n${coreJs}\n</script>`
);
out = out.replace(
  /<script\s+src="references\.js"><\/script>/,
  `<script>\n${refsJs}\n</script>`
);
out = out.replace(
  /<script\s+src="i18n\.js"><\/script>/,
  `<script>\n${i18nJs}\n</script>`
);
out = out.replace(
  /<script\s+src="app\.js"><\/script>/,
  `<script>\n${appJs}\n</script>`
);
out = inlineMedia(out);
out = out.replace(/\.\.\/assets\/brand\/favicon\.svg/g, `data:image/svg+xml;base64,${brandSvg}`);
out = inlineFonts(out);
out = out.replace(/href="\.\.\/(?!https?:)/g, 'href="../../');

function withBrandHomeHref(source, href) {
  return source.replace('<a class="brand-home" href="./index.html"', `<a class="brand-home" href="${href}"`);
}

// 3) Inject a small banner comment at the top
const banner =
`<!--
  Particle Zoo — SINGLE-FILE BUILD
  Generated by build.js from index.html + styles.css + i18n.js + app.js
  Do NOT edit this file directly; edit the source files and re-run:
      node build.js
  Source: https://github.com/micwu-personal/Physics
-->
`;
out = out.replace(/^<!DOCTYPE html>/i, `<!DOCTYPE html>\n${banner}`);

const outPath1 = path.join(OUT_DIR, 'index.html');
const outPath2 = path.join(OUT_DIR, 'particle-zoo.html');
fs.writeFileSync(outPath1, withBrandHomeHref(out, './index.html'));
fs.writeFileSync(outPath2, withBrandHomeHref(out, './particle-zoo.html'));

const sizeKB = (Buffer.byteLength(out, 'utf8') / 1024).toFixed(1);
console.log(`✓ Wrote ${outPath1} (${sizeKB} KB)`);
console.log(`✓ Wrote ${outPath2} (${sizeKB} KB)`);
console.log(`\nOpen the file directly in a browser or transfer to a phone.`);
