#!/usr/bin/env node
/*
  build.js — bundles big-bang into a single self-contained HTML file
  at mobile/index.html. Run with: node build.js  (from big-bang/)
*/
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT_DIR = path.join(ROOT, 'mobile');
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

const html   = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const css    = fs.readFileSync(path.join(ROOT, 'styles.css'), 'utf8');
const coreJs = fs.readFileSync(path.join(ROOT, 'core.js'), 'utf8');
const i18nJs = fs.readFileSync(path.join(ROOT, 'i18n.js'), 'utf8');
const appJs  = fs.readFileSync(path.join(ROOT, 'app.js'), 'utf8');

function inlineMedia(source) {
  return source.replace(/\.\.\/assets\/media\/([A-Za-z0-9_.-]+)/g, (match, filename) => {
    const filePath = path.join(ROOT, '..', 'assets', 'media', filename);
    if (!fs.existsSync(filePath)) throw new Error(`Missing media asset: ${filename}`);
    const mime = path.extname(filename).toLowerCase() === '.jpg' ? 'image/jpeg' : 'image/png';
    return `data:${mime};base64,${fs.readFileSync(filePath).toString('base64')}`;
  });
}

let out = html
  .replace(/<link\s+rel="stylesheet"\s+href="styles\.css"\s*\/?>/, `<style>\n${css}\n</style>`)
  .replace(/<script\s+src="core\.js"><\/script>/, `<script>\n${coreJs}\n</script>`)
  .replace(/<script\s+src="i18n\.js"><\/script>/, `<script>\n${i18nJs}\n</script>`)
  .replace(/<script\s+src="app\.js"><\/script>/, `<script>\n${appJs}\n</script>`);
out = inlineMedia(out);
out = out
  .replace(/href="\.\.\/index\.html/g, 'href="https://micwu-personal.github.io/Physics/')
  .replace(/href="\.\.\/(big-bang|particle-zoo|periodic-table)\/index\.html/g, 'href="https://micwu-personal.github.io/Physics/$1/');
out = out.replace(/href="\.\.\/(?!https?:)/g, 'href="../../');

const banner =
`<!--
  Big Bang — SINGLE-FILE BUILD
  Generated by build.js from index.html + styles.css + core.js + i18n.js + app.js
  Do NOT edit this file directly; edit the source files and re-run:
      node build.js
  Source: https://github.com/micwu-personal/Physics
-->
`;
out = out.replace(/^<!DOCTYPE html>/i, `<!DOCTYPE html>\n${banner}`);

const outPath = path.join(OUT_DIR, 'index.html');
fs.writeFileSync(outPath, out);

const sizeKB = (Buffer.byteLength(out, 'utf8') / 1024).toFixed(1);
console.log(`✓ Wrote ${outPath} (${sizeKB} KB)`);
